service: bootcamp

provider:
  name: aws
  runtime: python3.6
  timeout: 30
  memorySize: 128
  versionFunctions: false
  region: ap-southeast-1
  tags:
    Project: bootcamp
  iamRoleStatements:
    - Effect: Allow
      Action:
        - ec2:StartInstances
        - ec2:StopInstances
      Resource: 
        - arn:aws:ec2:::instance/${opt:instance}
    - Effect: Allow
      Action:
        - ec2:DescribeInstances
        - ec2:StartInstances
        - ec2:StopInstances
      Resource: 
        - '*'
package:
  exclude: 
functions:
  start:
    handler: control.start
    environment:
      instance: ${opt:instance}
    events:
      - http:
          path: /start
          method: get
  stop:
    handler: control.stop
    environment:
      instance: ${opt:instance}
    events:
      - http:
          path: /stop
          method: get
  check:
    handler: control.check
    environment:
      instance: ${opt:instance}
    events:
      - http:
          path: /check
          method: get